### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by milani** [Geeknux/node-jalali#1]
Hi,

May I ask you to rename the project? something like _node-jalali_ is beautiful.

**Comment by milani** [comment]
If you rename it I can help you on this project.

**Comment by Geeknux** [comment]
Hi, 
Yes, sure, why not. when I was starting this project, I just choose a name to submit on GitHub.
And now, I'm agree with you about the name, node-jalali is more beautiful and, It's self-explanatory
